on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
    types: [closed]

name: Deploy Web

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.repository == 'dlunch/wie_app' && (github.event_name == 'push' || github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-build-wasm-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-build-wasm-target-

      - name: Cache .npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: npm install
        working-directory: ./wie_web
        run: npm install

      - name: Build
        if: github.ref == 'refs/heads/release'
        working-directory: ./wie_web
        run: npm run build:prod

      - name: Build
        if: github.ref == 'refs/heads/main'
        working-directory: ./wie_web
        run: npm run build:dev

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "f02d26a267c8cc8f3fdd15e70e58f9f2"
          projectName: ${{ fromJSON('["wie-dev", "wie"]')[ github.ref != 'refs/heads/main' ] }}
          directory: "./wie_web/dist"
          branch: "main"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
