on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
    types: [closed]

name: Deploy Web

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.repository == 'dlunchp/wie_app'
    runs-on: arc-runner
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Install packages
        run: |
          sudo apt-get update;sudo apt-get install -y --no-install-recommends build-essential zstd

      - name: Restore cache cargo
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Restore cache cargo build
        uses: actions/cache/restore@v4
        with:
          path: target
          key: ${{ runner.os }}-build-wasm-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-build-wasm-target-

      - name: Restore cache .npm
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: npm install
        working-directory: ./wie_web
        run: npm install

      - name: Build
        if: github.ref == 'refs/heads/release'
        working-directory: ./wie_web
        run: npm run build:prod

      - name: Build
        if: github.ref == 'refs/heads/main'
        working-directory: ./wie_web
        run: npm run build:dev

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "f02d26a267c8cc8f3fdd15e70e58f9f2"
          projectName: ${{ fromJSON('["wie-dev", "wie"]')[ github.ref != 'refs/heads/main' ] }}
          directory: "./wie_web/dist"
          branch: "main"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"

      - name: Save cache cargo
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Save cache cargo build
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: target
          key: ${{ runner.os }}-build-wasm-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Save cache .npm
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
