name: Security audit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  audit:
    runs-on: arc-runner
    steps:
      - name: Install packages
        run: sudo apt update;sudo apt install -y --no-install-recommends build-essential zstd
        
      - name: Cache cargo registry
        uses: actions/cache/restore@v5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-audit-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache/restore@v5
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-audit-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache/restore@v5
        with:
          path: target
          key: ${{ runner.os }}-stable-build-target-audit-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - uses: dtolnay/rust-toolchain@stable
      
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
