on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

name: Web CI

jobs:
  web_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Install packages
        run: |
          sudo apt-get update;sudo apt-get install -y --no-install-recommends build-essential zstd

      - name: Restore cache cargo
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Restore cache cargo build
        uses: actions/cache/restore@v4
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.rust }}-build-wasm-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.rust }}-build-wasm-target-

      - name: Restore cache .npm
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: wasm32-unknown-unknown

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: npm install
        working-directory: ./wie_web
        run: npm install

      - name: Build
        working-directory: ./wie_web
        run: npm run build:dev

      - name: Save cache cargo
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Save cache cargo build
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: target
          key: ${{ runner.os }}-${{ matrix.rust }}-build-wasm-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Save cache .npm
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
